# Numpy

# Question 1: Data Creation and Inspection

In [41]:
#A data analyst often starts by creating or loading data. Let's create a 1D array representing daily sales over a week and then inspect it.
# 1)Create a NumPy array called daily_sales with the values [150, 200, 180, 220, 195, 250, 210].
# 2)Print the shape, size, and data type (dtype) of the array.
# 3)Find the total number of days in the sales data.
# 4)Print the first three days' sales data using slicing.


In [6]:
import numpy as np

daily_sales=np.array([150, 200, 180, 220, 195, 250, 210])
print(np.shape(daily_sales))
print(np.size(daily_sales))
print(daily_sales.dtype)
print(len(daily_sales))
print(daily_sales[:3])


(7,)
7
int64
7
[150 200 180]


# Question 2: Basic Array Operations

In [43]:
#Now,let's perform some calculations on the sales data.
# 1)Calculate and print the total sales for the week.
# 2)Calculate and print the average daily sales.
# 3)Find and print the highest and lowest sales recorded.
# 4)Calculate and print the standard deviation of the sales data. What does this value tell you about the sales figures?

In [11]:
print(np.sum(daily_sales))
print(np.mean(daily_sales))
print(np.min(daily_sales))
print(np.max(daily_sales))
print(np.std(daily_sales))
#In this case, the standard deviation will be around 29.1, which suggests moderate variability in daily sales.


1405
200.71428571428572
150
250
29.084675816431904


# Question 3: Manipulating and Filtering Data

In [44]:
#Analysts often need to modify and filter data to find specific insights.
# 1)A new sales figure of 230 came in for an additional day. Print the updated array.
# 2)Your manager wants to know which days had sales greater than the average daily sales. Use filtering to create a new array containing only the sales figures that are above the average. Print this new array.

In [13]:
print(np.append(daily_sales,230))
fil=daily_sales>200
new=daily_sales[fil]
print(new)

[150 200 180 220 195 250 210 230]
[220 250 210]


# Question 4: Working with 2D Arrays (Matrices)

In [ ]:
#Data is often organized in a 2D format, like a spreadsheet. Let's work with a 2D array representing sales for two different products over three days.
# 1)Create a 2D NumPy array called product_sales with the following data:
#Product 1: [100, 120, 90]
#Product 2: [150, 160, 170]
# 2)Print the shape and dimension of this array.
# 3)Using slicing, print the sales for Product 2 only.
# 4)calculate the total sales for each product. Use the axis parameter to achieve this without manually summing each row. Print the result.
# 5)Calculate the total sales for all products combined.

In [39]:
product_sales=np.array([[100, 120, 90],[150, 160, 170]])
print(np.shape(product_sales))
print(np.ndim(product_sales))
print(product_sales[1])
print(np.sum(product_sales[0]))
print(np.sum(product_sales[1]))
#0r
print(np.sum(product_sales, axis=1))
print(np.sum(product_sales))

(2, 3)
2
[150 160 170]
310
480
[310 480]
790


# Question 5: Advanced Operations

In [45]:
#Let's combine some of the concepts to perform a more complex task.
# 1)Two arrays represent the prices and quantities of items sold in a shop.
#prices = np.array([5.50, 2.75, 12.00, 8.50])
#quantities = np.array([10, 25, 5, 8])
# 2)Calculate the total revenue for each item by multiplying the prices and quantities arrays. Store the result in a new array called item_revenue.
# 3)Calculate and print the total revenue for the entire shop by summing the item_revenue array.
# 4)Assume the sales tax is 8%. Calculate and print the total revenue after tax.

In [40]:
prices = np.array([5.50, 2.75, 12.00, 8.50])
quantities = np.array([10, 25, 5, 8])
item_revenue=np.multiply(prices,quantities)
print(item_revenue)
print(np.sum(item_revenue))
After_TaxedRevenue=np.multiply(item_revenue,1.08)
print(After_TaxedRevenue)
print(np.sum(After_TaxedRevenue))



[55.   68.75 60.   68.  ]
251.75
[59.4  74.25 64.8  73.44]
271.89


# Practice Question 6: Data Simulation and Reshaping

In [46]:
#As a data analyst, you often need to work with simulated data for testing or modeling.
# 1)create a 1D array named monthly_data containing 30 random integers between 100 and 500. This array represents daily sales for a month.
# 2)The data is more useful when organized by weeks. Reshape the monthly_data array into a 2D array with 5 rows (representing weeks) and 6 columns (representing days of the week).
#Print the reshaped array and its new shape.

In [36]:
monthly_data=np.random.randint(100,500,30)
print(monthly_data)
print(monthly_data.reshape(5,6))

[238 400 357 479 366 196 311 270 207 494 458 220 242 487 132 171 317 470
 231 288 177 480 331 123 139 286 170 293 316 203]
[[238 400 357 479 366 196]
 [311 270 207 494 458 220]
 [242 487 132 171 317 470]
 [231 288 177 480 331 123]
 [139 286 170 293 316 203]]
